[package]
name = "vc0"
version = "0.1"
lean_version = "leanprover-community/lean:3.16.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "e40de30a5cee5fd7e6298f5075a9c840f55a34a6"}
